package com.hamalawey.domain.entities.item

import com.hamalawey.domain.entities.brand.Brand
import com.hamalawey.domain.entities.brand.Price
import com.hamalawey.domain.entities.brand.Promotion

data class ItemDetails(
    val brand: Brand,
    val calories: Any,
    val cost_price: Any,
    val description: String,
    val favorite: Any,
    val features: Features,
    val gtin: Any,
    val has_special_price: Boolean,
    val hide_quantity: Boolean,
    val id: Int,
    val images: List<Image>,
    val included_tax: Boolean,
    val is_available: Boolean,
    val main_image: String,
    val managed_by_branches: Boolean,
    val max_items_per_user: Int,
    val maximum_quantity_per_order: Int,
    val mpn: Any,
    val name: String,
    val notify_quantity: Any,
    val options: List<Any>,
    val pre_tax_price: Price,
    val price: Price,
    val promotion: Promotion,
    val quantity: Int,
    val rating: Rating,
    val regular_price: Price,
    val require_shipping: Boolean,
    val sale_end: Any,
    val sale_price: Price,
    val short_link_code: String,
    val show_in_app: Boolean,
    val show_purchase_count: Boolean,
    val sku: Any,
    val skus: List<Any>,
    val sold_quantity: Int,
    val sold_quantity_desc: String,
    val starting_price: Any,
    val status: String,
    val tags: List<Any>,
    val tax: Price,
    val taxed_price: Price,
    val type: String,
    val unlimited_quantity: Boolean,
    val url: String,
    val urls: Urls,
    val views: Any,
    val weight: Int,
    val with_tax: Boolean
)